- name: Deploy WordPress on vm1
  hosts: vm1
  become: true

  vars:
    doc_root: /var/www/html
    wp_tar: /tmp/wordpress.tar.gz
    wp_tmp: /tmp/wordpress
    wp_url: https://wordpress.org/latest.tar.gz

  tasks:
    - name: Update apt cache
      apt:
        update_cache: true

    - name: Install Apache and php
      apt:
        name:
          - apache2
          - php
          - libapache2-mod-php
          - php-xml
          - php-mbstring
          - php-mysql
          - php-zip
          - php-gd
          - php-curl
          - tar
        state: present

    - name: Enable Apache
      service:
        name: apache2
        enabled: true
        state: started

    - name: docroot
      file:
        path: "{{ doc_root }}"
        state: directory
        mode: "0755"

    - name: Remove index.html 
      file:
        path: "{{ doc_root }}/index.html"
        state: absent

    - name: Download WP 
      get_url:
        url: "{{ wp_url }}"
        dest: "{{ wp_tar }}"
        mode: "0644"

    - name: Remove any previous extracted temp dir
      file:
        path: "{{ wp_tmp }}"
        state: absent

    - name: Extract WordPress into /tmp
      unarchive:
        src: "{{ wp_tar }}"
        dest: /tmp
        remote_src: true

    - name: Copy WordPress files 
      copy:
        src: "{{ wp_tmp }}/"
        dest: "{{ doc_root }}/"
        owner: www-data
        group: www-data
        mode: "0755"
        remote_src: true

    - name: Ensure ownership of d
      file:
        path: "{{ doc_root }}"
        state: directory
        recurse: true
        owner: www-data
        group: www-data

    - name: Enable Apache rewrite module 
      command: a2enmod rewrite
      args:
        creates: /etc/apache2/mods-enabled/rewrite.load
      notify: restart apache

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
