- name: Deploy WordPress (Ubuntu, minimal)
  hosts: wordpress
  become: yes
  gather_facts: no
  vars:
    web_root: /var/www/html
    wp_url: https://wordpress.org/latest.tar.gz
    wp_tar: /tmp/wordpress.tar.gz
  tasks:
    - name: Install Apache + PHP (updates cache too)
      ansible.builtin.apt:
        name: [apache2, php, libapache2-mod-php, php-mysql, curl, tar]
        state: present
        update_cache: yes
    - name: Ensure Apache is enabled and running
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes
    - name: Download WordPress
      ansible.builtin.get_url:
        url: "{{ wp_url }}"
        dest: "{{ wp_tar }}"
        mode: '0644'
    - name: Extract WordPress into web root (strip top folder)
      ansible.builtin.unarchive:
        src: "{{ wp_tar }}"
        dest: "{{ web_root }}"
        remote_src: yes
        extra_opts: ["--strip-components=1"]
    - name: Remove default Apache index.html (if present)
      ansible.builtin.file:
        path: "{{ web_root }}/index.html"
        state: absent
    - name: Set ownership for web root
      ansible.builtin.file:
        path: "{{ web_root }}"
        owner: www-data
        group: www-data
        recurse: yes